name: TestCrossRepo

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test'
        required: true
        type: string


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Hello, ${{ github.actor }}"
  
  cross-repo-test:
    uses: cschadewitz/workflow-testing/.github/workflows/cross_repo_test_ru.yml@gh-to-azure-oidc-reusable-workflow
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}